/*
 * File: app/model/Question.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QAApp.model.Question', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'question',
            type: 'string'
        },
        {
            name: 'answer1',
            type: 'string'
        },
        {
            name: 'answer2',
            type: 'string'
        },
        {
            name: 'answer3',
            type: 'string'
        },
        {
            name: 'answer4',
            type: 'string'
        },
        {
            name: 'correctanswer',
            type: 'string'
        },
        {
            name: 'stream',
            type: 'string'
        },
        {
            name: 'level',
            type: 'string'
        },
        {
            name: 'submittedBy',
            type: 'string'
        }
    ]
});