/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QAApp.view.MainPanel', {
	extend : 'Ext.panel.Panel',
	alias : 'widget.QuizMainPanel',
	requires : [ 'QAApp.view.QuestionGrid', 'QAApp.view.QuestionForm' ],
        id: "Mainpanel",
	activeTab : 1,
	layout : {
		type : 'vbox',
		align : 'center'

	},
	initComponent : function() {
		var me = this;
		Ext.applyIf(me, {
			items : [ {
				xtype : 'questionform'
			},

			{
				xtype : 'questiongrid',
				width : '98%',
				autoScroll : true,
				height : 200
			}

			]
		});

		me.callParent(arguments);
	}

});